naganocake/config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get 'about', to: 'homes#about'
    get 'customers', to: 'redirects#customers'

    # customer
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    patch 'customers/withdraw_update' => 'customers#withdraw_update', as: 'withdraw_update'

    # item
    resources :items, only: [:index, :show]

    # cart_item
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'delete_all'
      end
    end

    # address
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    # order
    resources :orders, only: [:index, :new, :create, :show] do
      collection do
        post 'check', to: 'orders#check', as: 'check'
        get 'complete', to: 'orders#complete', as: 'complete'
      end
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top', as: 'admin'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        patch :toggle_status  
      end
      resources :addresses, only: [:index, :show, :edit, :update, :create, :destroy]
      resources :orders, only: [:index, :show]  # 会員に紐づく注文履歴
    end

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:new, :index, :create, :edit, :update, :show] do
      member do
        patch :toggle_status  # ← 商品の販売ステータス切り替え
      end
    end

    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
end

naganocake/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items,dependent: :destroy
  has_many :addresses,dependent: :destroy
  has_many :orders,dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
end

naganocake/app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
  
    def index
      @customers = Customer.all
      @customers = Customer.page(params[:page]).per(10)
    end
  
    def show
      @customer = Customer.find(params[:id])
      @addresses = @customer.addresses          # 顧客の配送先を取得
    end
  
    def edit
      @customer = Customer.find(params[:id])
    end
  
    def update
      @customer = Customer.find(params[:id])
      if @customer.update(customer_params)
        redirect_to admin_customer_path(@customer), notice: "顧客情報を更新しました。"
      else
        render :edit
      end
    end

    def toggle_status
      customer = Customer.find(params[:id])
      customer.update(is_deleted: !customer.is_deleted)
      redirect_to admin_customers_path, notice: "会員ステータスを変更しました。"
    end
  
    private
  
    def customer_params
      params.require(:customer).permit(
        :last_name, :first_name,
        :last_name_kana, :first_name_kana,
        :email, :postal_code,
        :address, :phone_number,
        :is_deleted 
      )
    end
  end
  

naganocake/app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

naganocake/app/views/admin/customers/edit.html.erb
<div class="container mt-4">
  <h2 class="text-center">会員情報編集</h2>
  <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
    
    <div class="mb-3">
      <%= f.label :last_name, "姓", class: "form-label" %>
      <%= f.text_field :last_name, class: "form-control", autofocus: true, autocomplete: "last_name" %>
    </div>

    <div class="mb-3">
      <%= f.label :first_name, "名", class: "form-label" %>
      <%= f.text_field :first_name, class: "form-control", autofocus: true, autocomplete: "first_name" %>
    </div>

    <div class="mb-3">
      <%= f.label :last_name_kana, "姓 (カナ)", class: "form-label" %>
      <%= f.text_field :last_name_kana, class: "form-control", autofocus: true, autocomplete: "last_name_kana" %>
    </div>

    <div class="mb-3">
      <%= f.label :first_name_kana, "名 (カナ)", class: "form-label" %>
      <%= f.text_field :first_name_kana, class: "form-control", autofocus: true, autocomplete: "first_name_kana" %>
    </div>

    <div class="mb-3">
      <%= f.label :email, "Email", class: "form-label" %>
      <%= f.email_field :email, class: "form-control", autofocus: true, autocomplete: "email" %>
    </div>

    <div class="mb-3">
      <%= f.label :postal_code, "郵便番号", class: "form-label" %>
      <%= f.text_field :postal_code, class: "form-control", autofocus: true, autocomplete: "postal_code" %>
    </div>

    <div class="mb-3">
      <%= f.label :address, "住所", class: "form-label" %>
      <%= f.text_field :address, class: "form-control", autofocus: true, autocomplete: "address" %>
    </div>

    <div class="mb-3">
      <%= f.label :phone_number, "電話番号", class: "form-label" %>
      <%= f.text_field :phone_number, class: "form-control", autofocus: true, autocomplete: "phone_number" %>
    </div>

    <div class="mb-3">
    <%= f.label :is_deleted, "ステータス", class: "form-label d-block" %>
    
    <div class="form-check form-check-inline">
      <%= f.radio_button :is_deleted, false, id: "customer_status_active", class: "form-check-input" %>
      <%= f.label :is_deleted, "有効", value: false, class: "form-check-label", for: "customer_status_active" %>
    </div>
  
    <div class="form-check form-check-inline">
      <%= f.radio_button :is_deleted, true, id: "customer_status_withdrawn", class: "form-check-input" %>
      <%= f.label :is_deleted, "退会", value: true, class: "form-check-label", for: "customer_status_withdrawn" %>
    </div>
    </div>

    <%= f.submit "更新", class: "btn btn-primary" %>
  <% end %>
</div>

naganocake/app/views/admin/customers/index.html.erb
<h1 class="my-4 text-center">会員一覧</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="thead-light">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>Email</th>
      <th>退会ステータス</th>
      <th>アクション</th>
    </tr>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to "#{customer.last_name} #{customer.first_name}", admin_customer_path(customer) %></td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_deleted == false %>
          <span class="badge bg-success">有効</span>
        <% else %>
          <span class="badge bg-danger">退会済</span>
        <% end %>
      </td>
      <td>
        <div class="d-flex gap-2">
          <% if customer.is_deleted %>
            <%= button_to "有効に戻す", toggle_status_admin_customer_path(customer),
                          method: :patch,
                          data: { confirm: "この会員を『有効』状態に戻しますか？" },
                          class: "btn btn-sm btn-success" %>
          <% else %>
            <%= button_to "退会にする", toggle_status_admin_customer_path(customer),
                          method: :patch,
                          data: { confirm: "この会員を『退会』状態にしますか？" },
                          class: "btn btn-sm btn-danger" %>
          <% end %>
          <%= link_to "会員の詳細", admin_customer_path(customer),
                      class: "btn btn-outline-secondary btn-sm" %>
        </div>
      </td>
    </tr>
  <% end %>
  </thead>
  </tbody>
</table>
<div class="d-flex justify-content-center my-4">
  <%= paginate @customers %>
</div>

naganocake/app/views/admin/customers/show.html.erb
<div class="container mt-4">
  <h2 class="text-center">Customer Page</h2>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td>カナ:</td>
        <td><%= @customer.last_name_kana %></td>
        <td><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>名前:</td>
        <td><%= @customer.last_name %></td>
        <td><%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td colspan="2"><%= @customer.email %></td>
      </tr>
      <tr>
        <td>郵便番号:</td>
        <td colspan="2"><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所:</td>
        <td colspan="2"><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号:</td>
        <td colspan="2"><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td colspan="3" class="text-center">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-outline-primary" %>
          <%= link_to "配送先一覧", admin_customer_addresses_path(@customer), class: "btn btn-outline-secondary" %>
          <%= link_to "注文履歴一覧", admin_customer_orders_path(@customer), class: "btn btn-outline-info" %>
        </td>
      </tr>
    </tbody>
  </table>
</div>