naganocake/config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get 'about', to: 'homes#about'
    get 'customers', to: 'redirects#customers'

    # customer
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    patch 'customers/withdraw_update' => 'customers#withdraw_update', as: 'withdraw_update'

    # item
    resources :items, only: [:index, :show]

    # cart_item
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'delete_all'
      end
    end

    # address
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    # order
    resources :orders, only: [:index, :new, :create, :show] do
      collection do
        post 'check', to: 'orders#check', as: 'check'
        get 'complete', to: 'orders#complete', as: 'complete'
      end
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top', as: 'admin'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        patch :toggle_status  
      end
      resources :addresses, only: [:index, :show, :edit, :update, :create, :destroy]
      resources :orders, only: [:index, :show]  # 会員に紐づく注文履歴
    end

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:new, :index, :create, :edit, :update, :show] do
      member do
        patch :toggle_status  # ← 商品の販売ステータス切り替え
      end
    end

    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
end

naganocake/app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :oder_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  # バリデーション
  # validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, numericality: true
  # validates :genre_id, presence: { message: "を入力してください" }

  # その他のメソッド
  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.recommended
    recommends = []
    active_genres = Genre.only_active.includes(:items)
    active_genres.each do |genre|
      item = genre.items.last
      recommends << item if item
    end
    recommends
  end
end

naganocake/app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:search] == "perfect_match"
      @items = Item.where("name LIKE ?", "#{params[:word]}")
    elsif params[:search] == "forward_match"
      @items = Item.where("name LIKE ?", "#{params[:word]}%")
    elsif params[:search] == "backward_match"
      @items = Item.where("name LIKE ?", "%#{params[:word]}")
    elsif params[:search] == "partial_match"
      @items = Item.where("name LIKE ?", "%#{params[:word]}%")
    else
      @items = Item.all
    end
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def edit
    @item = Item.find(params[:id])  # 既存のアイテムを取得
    @genre = Genre.all  # ジャンルの情報を取得
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "登録成功"
      redirect_to admin_item_path(@item)
    else
      @genre = Genre.all
      render :new  # エラー表示のために @item をビューに渡す
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "商品情報が更新されました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  # 販売ステータスを切り替えるアクション
  def toggle_status
    @item = Item.find(params[:id])
    @item.update(is_deleted: !@item.is_deleted)  # ステータスを反転
    redirect_to admin_items_path, notice: "販売ステータスが変更されました。"
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :image, :genre_id, :introduction, :is_deleted)
  end
  
end

naganocake/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

naganocake/app/views/admin/items/edit.html.erb
<%= render 'admin/shared/error_messages', resource: @item %>

<div class="container mt-4">
  <h1 class="my-4 text-center">編集</h1>

  <%= form_with model: @item, url: admin_item_path(@item), method: :patch, class: "form" do |f| %>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :image, "画像", class: "form-label" %>
        <%= f.file_field :image, class: "form-control", accept: "image/*" %>
      </div>

      <div class="col-md-6">
        <%= f.label :name, "商品名", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "商品名" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :introduction, "説明", class: "form-label" %>
        <%= f.text_field :introduction, class: "form-control", placeholder: "説明文" %>
      </div>

      <div class="col-md-6 genre_field">
        <%= f.label :genre_id, "ジャンル", class: "form-label" %><br>
        <%= f.collection_select :genre_id, @genre, :id, :name, { prompt: "ジャンル名" }, class: "form-select" %>
      </div>

      <div class="col-md-6">
        <%= f.label :price, "価格（円）", class: "form-label" %>
        <%= f.number_field :price, class: "form-control", min: 0, step: 1, placeholder: "価格を入力してください" %>
      </div>
    </div>

      <div class="row mb-3">
      <div class="col-md-6 is_deleted_field">
        <label class="form-label">販売ステータス</label>
        <div class="form-check">
          <%= f.radio_button :is_deleted, false, class: "form-check-input" %>
          <%= f.label :is_deleted, "販売中", value: false, class: "form-check-label" %>
        </div>
        <div class="form-check">
          <%= f.radio_button :is_deleted, true, class: "form-check-input" %>
          <%= f.label :is_deleted, "販売停止中", value: true, class: "form-check-label" %>
        </div>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= f.submit '更新', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

naganocake/app/views/admin/items/index.html.erb
<h1 class="my-4 text-center">商品一覧 (admin)</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead class="thead-light">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>販売ステータス</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item) %></td>
          <td><%= number_to_currency(item.price, unit: "¥", format: "%u%n") %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_deleted %>
              <span class="badge bg-danger">停止中</span>
            <% else %>
              <span class="badge bg-success">販売中</span>
            <% end %>
          </td>
          <td style="white-space: nowrap;">
          <!-- 販売ステータス切り替えボタン -->
            <% if item.is_deleted %>
              <%= button_to "販売再開", toggle_status_admin_item_path(item),
                          method: :patch,
                          data: { confirm: "この商品を販売中に戻しますか？" },
                          class: "btn btn-sm btn-success" %>
            <% else %>
              <%= button_to "販売停止", toggle_status_admin_item_path(item),
                          method: :patch,
                          data: { confirm: "この商品を販売停止にしますか？" },
                          class: "btn btn-sm btn-warning" %>
            <% end %>
            <!-- 商品の編集ボタン -->
            <%= link_to '商品の編集', edit_admin_item_path(item), class: "btn btn-sm btn-secondary ms-1" %>

            <!-- 商品の詳細ボタン -->
            <%= link_to '商品の詳細', admin_item_path(item), class: "btn btn-sm btn-info ms-1" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- ページネーションの表示 -->
<div class="d-flex justify-content-center my-4">
  <%= paginate @items %>
</div>

<div class="text-center mt-4">
  <%= link_to "商品新規登録", new_admin_item_path, class: "btn btn-primary" %>
</div>

naganocake/app/views/admin/items/new.html.erb
<%= render 'admin/shared/error_messages', resource: @item %><!-- 部分テンプレートファイル -->

<div class="container mt-4">
  <h1 class="my-4 text-center">商品登録</h1>

  <%= form_with model: @item, url: admin_items_path, class: "form" do |f| %>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :image, "商品画像", class: "form-label" %>
        <%= f.file_field :image, class: "form-control", accept: "image/*" %>
      </div>

      <div class="col-md-6">
        <%= f.label :name, "商品名", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "商品名" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :introduction, "説明文", class: "form-label" %>
        <%= f.text_field :introduction, class: "form-control", placeholder: "説明文", style: "height: calc(2.25rem + 2px);" %>
      </div>

      <div class="col-md-6 genre_field">
        <%= f.label :genre_id, "ジャンル", class: "form-label" %><br>
        <%= f.collection_select :genre_id, @genre, :id, :name, { prompt: "ジャンル名" }, class: "form-select", style: "height: calc(2.25rem + 2px);" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :price, "値段", class: "form-label" %>
        <%= f.text_field :price, class: "form-control", placeholder: "値段" %>
      </div>

      <div class="col-md-6 is_deleted_field">
        <label class="form-label">販売ステータス</label>
        <div class="form-check">
          <%= f.radio_button :is_deleted, "false", class: "form-check-input" %>
          <%= f.label :is_deleted, "販売中", value: "false", class: "form-check-label" %>
        </div>
        <div class="form-check">
          <%= f.radio_button :is_deleted, "true", class: "form-check-input" %>
          <%= f.label :is_deleted, "販売停止中", value: "true", class: "form-check-label" %>
        </div>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= f.submit '追加', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

naganocake/app/views/admin/items/show.html.erb
<h3 class="text-center my-5">商品詳細</h3>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="text-center">
        <%= image_tag @item.get_item_image(400,400), class: "img-fluid rounded shadow-sm" %>
      </div>
    </div>
    <div class="col-md-6">
      <h2 class="mb-4 font-weight-bold"><%= @item.name %></h2>

      <p class="lead"><%= @item.introduction %></p>

      <!-- ジャンル -->
      <p><strong>ジャンル:</strong> <%= @item.genre.name %></p>

      <!-- 販売ステータス -->
      <p><strong>販売ステータス:</strong>
      <%= @item.is_deleted ? "販売停止中" : "販売中" %>
      </p>

      <!-- 税込価格 -->
      <h4 class="text-primary">税込価格: <%= @item.with_tax_price %>円</h4>

      <!-- 編集リンク -->
      <%= link_to '商品を編集する', edit_admin_item_path(@item), class: "btn btn-outline-primary mt-4" %>
    </div>
  </div>
</div>