naganocake/config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get 'about', to: 'homes#about'
    get 'customers', to: 'redirects#customers'

    # customer
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    patch 'customers/withdraw_update' => 'customers#withdraw_update', as: 'withdraw_update'

    # item
    resources :items, only: [:index, :show]

    # cart_item
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'delete_all'
      end
    end

    # address
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    # order
    resources :orders, only: [:index, :new, :create, :show] do
      collection do
        post 'check', to: 'orders#check', as: 'check'
        get 'complete', to: 'orders#complete', as: 'complete'
      end
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top', as: 'admin'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        patch :toggle_status  
      end
      resources :addresses, only: [:index, :show, :edit, :update, :create, :destroy]
      resources :orders, only: [:index, :show]  # 会員に紐づく注文履歴
    end

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:new, :index, :create, :edit, :update, :show] do
      member do
        patch :toggle_status  # ← 商品の販売ステータス切り替え
      end
    end

    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
end

naganocake/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Font Awesome 読み込み -->
    <script src="https://kit.fontawesome.com/9e2ec3ed1e.js" crossorigin="anonymous"></script>

    <style>
      /* ナビゲーションリンク */
      .navbar-nav {
        display: flex;
        flex-wrap: nowrap;
      }

      .navbar-nav .nav-item .nav-link {
        color: #fff;
        padding: 10px 7px;
        transition: background-color 0.3s ease, color 0.3s ease;
        white-space: nowrap; 
      }

      /* ホバー時エフェクト */
      .navbar-nav .nav-item .nav-link:hover {
        background-color: #008b8b;
        color: #fff;
        border-radius: 5px;
      }

      /* 検索ボックス */
      .search-form input[type="text"] {
        border: 1px solid #ccc;
        padding: 5px;
        border-radius: 5px;
      }

      /* 検索ボタン */
      .search-form button {
        background-color: #ff6347;
        border: none;
        color: white;
        padding: 5px 10px;
        border-radius: 5px;
        cursor: pointer;
      }

      .navbar-brand {
        font-size: 1.8rem;
        font-weight: bold;
        color: #ff6347;
        transition: color 0.3s ease;
      }

      .navbar-brand:hover {
        color: #fff;
      }

      /* Admin の場合の検索フォームの幅 */
      .admin-search-form {
        flex-grow: 1;  /* 検索フォームが他の要素を押しのけるように横幅を広げる */
        max-width: 500px;  /* 必要に応じて最大幅を設定 */
      }

      /* 通常の検索フォームの幅 */
      .search-form {
        max-width: 300px; /* デフォルトの検索フォームの最大幅 */
      }
    </style>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>    
                <!-- Admin ログイン時にクラスを付与 -->
                <a class="navbar-brand p-3" href="/admin">NaganoCake</a>
                <%= form_with url: admin_items_path, method: :get, class: 'search-form admin-search-form d-flex align-items-center mr-3' do |f| %>
                  <%= text_field_tag :word, params[:word], placeholder: "商品名で検索", class: "form-control mr-2" %>
                  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, class: "form-control mr-2" %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                <% end %>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-box"></i> 商品一覧'.html_safe, admin_items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-users"></i> 会員一覧'.html_safe, admin_customers_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                <%= link_to '<i class="fas fa-receipt"></i> 注文履歴一覧'.html_safe, admin_orders_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-tags"></i> ジャンル一覧'.html_safe, admin_genres_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-sign-out-alt"></i> ログアウト'.html_safe, destroy_admin_session_path, method: :delete, class: 'nav-link' %>
                </li>
              <% else %>
                <% if customer_signed_in? %>
                <a class="navbar-brand p-3" href="/">NaganoCake</a>
                <%= form_with url: admin_items_path, method: :get, class: 'search-form admin-search-form d-flex align-items-center mr-3' do |f| %>
                  <%= text_field_tag :word, params[:word], placeholder: "商品名で検索", class: "form-control mr-2" %>
                  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, class: "form-control mr-2" %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                <% end %>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-user"></i> マイページ'.html_safe, my_page_path, class: 'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-box"></i> 商品一覧'.html_safe, items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-shopping-cart"></i> カート'.html_safe, cart_items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-sign-out-alt"></i> ログアウト'.html_safe, destroy_customer_session_path, method: :delete, class: 'nav-link' %>
                </li>
                <% else %>
                 <li class="nav-item">
                  <%= link_to '<i class="fas fa-box"></i> About'.html_safe, about_path, class: 'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-box"></i> 商品一覧'.html_safe, items_path, class: 'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-user-plus"></i> 新規登録'.html_safe, new_customer_registration_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to '<i class="fas fa-sign-in-alt"></i> ログイン'.html_safe, new_customer_session_path, class: 'nav-link' %>
                </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <%= yield %>
    </main>
  </body>
</html>